type: web
name: chainsync-web
buildCommand: npm run build
startCommand: npm start
env: production
envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 3000
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: SESSION_SECRET
    value: ${SESSION_SECRET}
  - key: ALLOWED_ORIGINS
    value: ${ALLOWED_ORIGINS}
  - key: PAYSTACK_SECRET_KEY
    value: ${PAYSTACK_SECRET_KEY}
  - key: PAYSTACK_PUBLIC_KEY
    value: ${PAYSTACK_PUBLIC_KEY}
  - key: FLUTTERWAVE_SECRET_KEY
    value: ${FLUTTERWAVE_SECRET_KEY}
  - key: FLUTTERWAVE_PUBLIC_KEY
    value: ${FLUTTERWAVE_PUBLIC_KEY}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: GOOGLE_CLOUD_PROJECT_ID
    value: ${GOOGLE_CLOUD_PROJECT_ID}
  - key: GOOGLE_APPLICATION_CREDENTIALS
    value: ${GOOGLE_APPLICATION_CREDENTIALS}
  - key: REDIS_URL
    value: ${REDIS_URL}
  - key: CACHE_TTL
    value: ${CACHE_TTL}
  - key: LOG_LEVEL
    value: ${LOG_LEVEL}
  - key: RATE_LIMIT_WINDOW
    value: ${RATE_LIMIT_WINDOW}
  - key: RATE_LIMIT_MAX
    value: ${RATE_LIMIT_MAX}
git:
  repo: https://github.com/chainsyncstore/ChainSync.git
  branch: main
