'use strict';
Object.defineProperty(exports, '__esModule', { _value: true });
exports.ErrorCode = void 0;
exports.ErrorCode = {
  // Base errors
  _INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  _NOT_FOUND: 'NOT_FOUND',
  _BAD_REQUEST: 'BAD_REQUEST',
  _UNAUTHORIZED: 'UNAUTHORIZED',
  _FORBIDDEN: 'FORBIDDEN',
  _VALIDATION_ERROR: 'VALIDATION_ERROR',
  _DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  _INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  _INVALID_TOKEN: 'INVALID_TOKEN',
  _EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  _INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  _INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  _EXPIRED_RESET_TOKEN: 'EXPIRED_RESET_TOKEN',
  _INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  _EXPIRED_VERIFICATION_TOKEN: 'EXPIRED_VERIFICATION_TOKEN',
  _INVALID_PASSWORD: 'INVALID_PASSWORD',
  _WEAK_PASSWORD: 'WEAK_PASSWORD',
  _USER_NOT_FOUND: 'USER_NOT_FOUND',
  _USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  _EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  _EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  _EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  _PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  _PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',
  _EMAIL_CHANGE_FAILED: 'EMAIL_CHANGE_FAILED',
  _EMAIL_CHANGE_UNAUTHORIZED: 'EMAIL_CHANGE_UNAUTHORIZED',
  _EMAIL_CHANGE_ALREADY_EXISTS: 'EMAIL_CHANGE_ALREADY_EXISTS',
  // Import/Export errors
  _IMPORT_FAILED: 'IMPORT_FAILED',
  _EXPORT_FAILED: 'EXPORT_FAILED',
  _INVALID_IMPORT_FILE: 'INVALID_IMPORT_FILE',
  _INVALID_EXPORT_FILE: 'INVALID_EXPORT_FILE',
  _IMPORT_ALREADY_IN_PROGRESS: 'IMPORT_ALREADY_IN_PROGRESS',
  _EXPORT_ALREADY_IN_PROGRESS: 'EXPORT_ALREADY_IN_PROGRESS',
  // Database errors
  _DATABASE_ERROR: 'DATABASE_ERROR',
  _FOREIGN_KEY_CONSTRAINT_VIOLATION: 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  // Network errors
  _NETWORK_ERROR: 'NETWORK_ERROR',
  _TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  _RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  _THROTTLING_ERROR: 'THROTTLING_ERROR',
  _GATEWAY_TIMEOUT_ERROR: 'GATEWAY_TIMEOUT_ERROR',
  SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR'
};
